### ISSUE TITLE
Inconsistent next focused tab when closing child tabs

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1471]
## Short description
Inconsistent next focused tab when closing child tabs. These focus on cases where closing a child tab either focuses the previous child tab or the parent tab.

I'm not sure whether the correct behavior should be the previous tab or the parent tab, but either way, it should be consistent.

I've also had cases where the next root tab is focused instead, but I can't consistently reproduce.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.

### Case I: simple case
 3. Start from a single root tab A
 4. Open two child tabs B and C
 5. Select tab C:
```
A
|- B
\- C (selected)
```
 6. Close tab C

### Case II: create subsequent child tab after selecting parent tab again
 3. Start from a single root tab A
 4. Open child tab B
 5. Select tab B:
```
A
\- B (selected)
```
 6. Select tab A
 7. Create child tab C
 8. Select tab C:
```
A
|- B
\- C (selected)
```
 9. Close tab C

### Case III: same as Case II except with another child tab
 3. Start from a single root tab A
 4. Open child tab B
 5. Select tab B:
```
A
\- B (selected)
```
 6. Select tab A
 7. Create child tabs C and D
 8. Select tab D:
```
A
|- B
|- C
\- D (selected)
```
 9. Close tab D

### Case IV: same as Case III except closing tab C
 3. Start from a single root tab A
 4. Open child tab B
 5. Select tab B:
```
A
\- B (selected)
```
 6. Select tab A
 7. Create child tabs C and D
 8. Select tab C:
```
A
|- B
|- C (selected)
\- D
```
 9. Close tab C

### Case V: same as Case II except selecting tab B then tab C before closing tab C
 3. Start with a single root tab A
 4. Open child tab B
 5. Select tab B:
```
A
\- B (selected)
```
 6. Select tab A
 7. Create child tab C
 8. Select tab C:
```
A
|- B
\- C (selected)
```
 9. Select tab B:
```
A
|- B (selected)
\- C
```
 10. Select tab C again:
```
A
|- B
\- C (selected)
```
 11. Close tab C

### Case VI: same as Case II except with an undo close tab
 3. Reproduce Case II (parent tab is selected):
```
A (selected)
\- B
```
 4. Undo close tab:
```
A
|- B
\- C (selected)
```
 5. Close tab C again

### Case VII: same as Case I except closing tab B
 3. Start from a single root tab A
 4. Create child tabs B and C
 5. Select tab B:
```
A
|- B (selected)
\- C
```
 6. Close tab B

### Case VIII: same as Case V except with another child tab
 3. Start from a single root tab A
 4. Open child tab B
 5. Select tab B:
```
A
\- B (selected)
```
 6. Select tab A
 7. Create child tabs C and D
 8. Select tab C:
```
A
|- B
|- C (selected)
\- D
```
 9. Select tab B:
```
A
|- B (selected)
|- C
\- D
```
 10. Select tab C again:
```
A
|- B
|- C (selected)
\- D
```
 11. Close tab C

## Expected result
Should consistently either select previous tab or the parent tab. I'm not sure which is the correct behavior, but it should be consistent in all cases.

### Case I: simple case
Previous tab is selected:
```
A
\- B (selected)
```

### Case II: create subsequent child tab after selecting parent tab again
Parent tab is selected:
```
A (selected)
\- B
```

### Case III: same as Case II except with another child tab
Parent tab is selected:
```
A (selected)
|- B
\- C
```

### Case IV: same as Case III except closing tab C
Parent tab is selected:
```
A (selected)
|- B
\- D
```

### Case V: same as Case II except selecting tab B then tab C before closing tab C
Previous tab is selected:
```
A
\- B (selected)
```

### Case VI: same as Case II except with an undo close tab
Previous tab is selected:
```
A
\- B (selected)
```

### Case VII: same as Case I except closing tab B
Next tab is selected:
```
A
\- C (selected)
```

### Case VIII: same as Case V except with another child tab
Next tab is selected:
```
A
|- B
\- D (selected)
```

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b8
 * Version (or revision) of Tree Style Tab: 2.05

**Comment by lbmaian** [comment]
Added another case when undo close tab is used.

**Comment by lbmaian** [comment]
Oh forgot to add the cases where the next tab is selected.

**Comment by lbmaian** [comment]
Okay added cases where next tab is selected, and cleaned up cases overall.

**Comment by piroor** [comment]
TST now respects Firefox's `browser.tabs.selectOwnerOnClose`=`true` behavior, so if it is triggered by this feature I think TST should keep it and only wrong focuses not related to the feature should be fixed. (See also #1410)

**Comment by lbmaian** [comment]
Okay, so if ``browser.tabs.selectOwnerOnClose`` is enabled, closing a tab should consistently move focus back to parent tab?

Also, I just realized that the previous tab and next tab behavior is probably the same set of behavior:
1. if only child tab, select parent tab
2. else if last child tab, select previous sibling tab
3. else select next tab

**Comment by piroor** [comment]
Sorry, I cannot answer about the feature `browser.tabs.selectOwnerOnClose` because it is very very complex for me and I gave up to understand its complete behavior... thus TST detects only one case: the "owner" tab is NOT focused. If the owner is not focused, TST tries to move focus:

 * If there is no other child (it is the last child tab), focus to the parent instead of the next tab. (overridden behavior by TST)
 * If there is no next sibling but any preceding sibling, focus to the previous sibling instead of the next tab. (overridden behavior by TST)
 * If there is no child and no parent, then focus to the next tab. (Firefox's default behavior - TST does nothing on this case)

**Comment by lbmaian** [comment]
I just went ahead and disabled ``browser.tabs.selectOwnerOnClose``, since I agree that "feature" is just confounding. Not gonna close this myself since I do think there is still a problem when the feature is enabled; it's just not clear what the behavior should be exactly.

**Comment by piroor** [comment]
I close this because outdated. Now TST has ability to control successor tabs.
