### ISSUE TITLE
"Don't expand collapsed tree when using Ctrl(-Shift)-Tab" pref UI doesn't work? (with Ctrl+PgUp/PgDn)

### ISSUE THREAD

**Issue by ildar** [piroor/treestyletab#1718]
TST 2.4.3
Having two trees one below the other, both collapsed.
If I Ctrl+PgDn from the top, it gets expanded.
If I Ctrl+PgUp from the bottom, top tree gets expanded.

This is the follow-up of https://github.com/piroor/treestyletab/issues/1583

**Comment by piroor** [comment]
Please fill [the template of issue](https://github.com/piroor/treestyletab/blob/master/ISSUE_TEMPLATE.md). Too less information report make solving of the issue hard.

**Comment by piroor** [comment]
One more note: steps to reproduce with actual URLs are very helpful. Due to some reasons the hack for Ctrl-Tab doesn't work on some pages like about:addons, addons.mozilla.org, and others.

**Comment by ildar** [comment]
## Short description
"Don't expand collapsed tree when using Ctrl(-Shift)-Tab" pref UI doesn't
work? (with Ctrl+PgUp/PgDn)

## Steps to reproduce
1. Start Firefox with clean profile.
2. Install TST.
3. Open https://github.com/piroor/treestyletab/issues/
4. Right-click on any link, open in new tab (should generate a subtree)
3. Open new tab, https://github.com/piroor/treestyletab/issues/
4. Right-click on any link, open in new tab (should generate another
subtree)
Should look like:
https://github.com/piroor/treestyletab/issues/ (selected, collapsed)
\\- https://github.com/piroor/treestyletab/issues/1718
https://github.com/piroor/treestyletab/issues/ (collapsed)
\\- https://github.com/piroor/treestyletab/issues/1717
5. collapse all
6. Navigate to the top collapsed subtree
7. Push Ctrl+PgDn

## Expected result
Selected tab now is the 3rd

## Actual result
Selected tab now is the 2nd and the 1-2 subtree gets expanded

## Environment

* Platform (OS): Linux x86_64
* Version of Firefox: 57.0.4
* Version (or revision) of Tree Style Tab: 2.4.3

**Comment by piroor** [comment]
Thanks a lot, the commit eda7ed5 should fix this problem. Finally I realized that I missed comments around Ctrl-PageDown/Up...

**Comment by ildar** [comment]
Thanks!

**Comment by ildar** [comment]
Thanks a lot! Just tested it.
Navigation now works allright and the keystroke brings me where expected.
But unfortunately it isn't still 100% right: when I "jump over" then the
inner tab (1718 in
https://github.com/piroor/treestyletab/issues/1718#issuecomment-358548686)
still gets focus for a fraction of a second.
How do I know that? If the FF is just started then the inner tab is in
"sleeping state" i.e. unloaded. Jumping over makes it load.

**Comment by piroor** [comment]
It is due to WebExtensions-based addon's restrictions. WE-addons cannot disable keyboard shortcuts of Firefox itself, so Ctrl-PageUp/Down and Ctrl-Tab/Ctrl-Shift-Tab shortcut keys are always handled by Firefox (and it unexpectedly loads such pending tabs). TST just re-focus to expected next focused tab after Firefox does.

**Comment by ildar** [comment]
Oh! That's totally fine. Much better then nothing, right? 😉
Thanks a lot.
