### ISSUE TITLE
Sidebar never loads

### ISSUE THREAD

**Issue by ksulli** [piroor/treestyletab#1735]
## Short description
I restarted FF today, and the tree never loads. I just get an infinite animation. 

## Steps to reproduce

 1. Restart firefox or disable and enable extension
 2. Wait for the tree to load

## Expected result
Tree loads, it has been normally working for several months

## Actual result
![image](https://user-images.githubusercontent.com/765353/35431974-dc0dce50-027e-11e8-9adc-521336e68792.png)

## Environment

 * Platform (OS): Win 7
 * Version of Firefox: 57.0.4
 * Version (or revision) of Tree Style Tab: 2.4.5

**Comment by ksulli** [comment]
I found a workaround

1. Enable debug mode
1. Disable "Optimize tree restoration with cache"
1. Disable and re-enable addon. Tree loads (slowly, but loads).
1. Enable "Optimize tree restoration with cache" again
1. Tree stops loading

So I'm able to reproduce the broken state in my profile.

When I start with a clean profile, TST loads normally.

**Comment by piroor** [comment]
The startup tab can triggers fatal error on the initialization process. I've introduced some more fixes about this problem on TST 2.4.6.

**Comment by ksulli** [comment]
I tried it with 2.4.6 and the problem persists - if I have "Optimize tree restoration with cache" enabled, after restart of FF it doesn't load the sidebar. I disabled it again.

**Comment by blipp** [comment]
I have the same issue with TST 2.4.6 in FF 57.0.4. @ksulli's workaround works for me: with the disabled option, the tree loads.

**Comment by blipp** [comment]
I am on FF 58.0 now and the problem is gone :)

(I re-enabled the above mentioned cache option, disabled debug, restarted FF)

**Comment by kindofbeard** [comment]
Hello, I have this problem since the FF 58.0 update: tab bar displays the "loading" icon forever. 
I have 3 windows open. Windows 10 here btw.

**Comment by zertrin** [comment]
Same problem here, problem started with TST 2.4.5 and is still there with version 2.4.6 and FF Developer edition. I reverted to TST 2.4.3 in the meantime.

**Comment by jsams** [comment]
also seeing this with TST 2.4.6 and FF 58 on ubuntu. ksull's workaround also works for me. Guess that means there's a bug in the caching system? I do have like 200 tabs open in one window and 1000 in another. In another profile, I do not see a problem

**Comment by piroor** [comment]
To all: Could you try to reproduce the problem with enabled "Debug mode" checkbox? In the debug mode you'll see detailed logs like https://github.com/piroor/treestyletab/issues/1742#issuecomment-361172325 in the debugger window. ([How to start debugger for TST](https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-start-debugger-for-tree-style-tab))

**Comment by ksulli** [comment]
```
tst<BG>:         fixupTabRestoredFromCache parent:  null  common.js:21
tst<BG>:         fixupTabRestoredFromCache parent: =>  null  common.js:21
tst<BG>:         fixupTabRestoredFromCache children:  |tab-3-22|  common.js:21
tst<BG>:         fixupTabRestoredFromCache children: =>  |tab-3-22|  common.js:21
tst<BG>:         fixupTabRestoredFromCache parent:  tab-3-247  common.js:21
tst<BG>:         fixupTabRestoredFromCache parent: =>  tab-3-247  common.js:21
tst<BG>:      TypeError: aTab.apiTab is undefined isGroupTab@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/common/tree/tab-information.js:142:1
reserveToUpdateParentGroupTab@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/background/background.js:668:8
onTabLabelUpdated@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/background/handlers.js:772:3
updateTab@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/common/tree/base.js:230:33
fixupTabRestoredFromCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/common/tree/cache.js:189:5
fixupTabsRestoredFromCache/<@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/common/tree/cache.js:148:5
fixupTabsRestoredFromCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/common/tree/cache.js:147:3
restoreTabsFromCacheInternal@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/common/tree/cache.js:114:5
restoreTabsFromCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/background/cache.js:93:10
restoreWindowFromEffectiveWindowCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/background/cache.js:74:18
  common.js:21
tst<BG>:    restoreWindowFromEffectiveWindowCache: got from the owner 315 Object { cachedSignature: "tab-intrepid-zapus-1517227180889-145", cache: Object }  common.js:21
tst<BG>:    restoreWindowFromEffectiveWindowCache: verify cache for 19 Object { cache: Object, actualSignature: "tab-intrepid-zapus-1517227180889-145", cachedSignature: "tab-intrepid-zapus-1517227180889-145", signatureMatched: true }  common.js:21
tst<BG>:    restoreWindowFromEffectiveWindowCache: restore 19 from cache  common.js:21
tst<BG>:      restoreTabsFromCacheInternal: restore tabs for 19 from cache  common.js:21
tst<BG>:      restoreTabsFromCacheInternal: restore  common.js:21
tst<BG>:       
<ul data-window-id="53" id="window-53" class="tabs" data-duplicating-tabs-count="0" data-trying-reforcus-for-closing-current-tab-count="0" data-internal-silently-focus-count="0" data-internal-focus-count="0" data-doing-intelligently-collapse-expand-count="0" data-sub-tree-children-moving-count="0" data-sub-tree-moving-count="0" data-already-moved-tabs-count="0" data-internal-closing-count="0" data-internal-moving-count="0" data-prevent-auto-group-new-tabs-until="1517227180883" data-opening-count="0" data-opened-new-tabs="" data-opened-new-tabs-openers="" data-to-be-opened-tabs-with-positions="0" data-to-be-opened-orphan-tabs="0" data-to-be-attached-tabs="0" data-to-be-detached-tabs="0">
<li id="tab-53-313" data-tab-id="313" data-window-id="53" class="tab active subtree-collapsed contextual-identity-firefox-default complete" data-persistent-id="tab-intrepid-zapus-1517227180889-145" data-current-uri="***" data-label="***"><span class="label">***</span></li></ul>  common.js:21
tst<BG>:      restoreTabsFromCacheInternal: post process  <unavailable>  common.js:21
tst<BG>:       fixupTabsRestoredFromCache start  Object { elements: Array[1], apiTabs: Array[1] }  common.js:21
tst<BG>:        fixupTabsRestoredFromCache: remap tab-53-313 => tab-19-315  common.js:21
tst<BG>:         fixupTabRestoredFromCache children:  null  common.js:21
tst<BG>:         fixupTabRestoredFromCache children: =>  null  common.js:21
tst<BG>:         fixupTabRestoredFromCache parent:  null  common.js:21
tst<BG>:         fixupTabRestoredFromCache parent: =>  null  common.js:21
tst<BG>:      restoreTabsFromCacheInternal: done  common.js:21
tst<BG>:       dumpAllTabs
tab-19-315  common.js:21
tst<BG>:    window 19 is restored from cache  common.js:21
TypeError: aTab.apiTab is undefined
```

**Comment by piroor** [comment]
@ksulli Thanks a lot! Your log really helped me. I think recent commits should fix this problem.

**Comment by ksulli** [comment]
@piroor i retested with the new version it looks like it's fixed, tabs seem to be restored correctly even when chache restore is enabled

**Comment by Nexen23** [comment]
I has the same problem. First start (and often second one) sidebar never loads. Version 2.4.18

**Comment by Crell** [comment]
Unfortunately I am still seeing this issue.  Freshly restarted Firefox so it's fully up to date as of today (13 May.)

**Comment by tkhquang** [comment]
This problem only seems to happen if I have `extensions.webextensions.remote` set to `true` on my side.

**Comment by gonhidi** [comment]
On sidebar loading success, with tree restoration with cache disabled, I see `gMetricsData.toString()` output the above. On failure, when the cache optimization is enabled, I get the following:

```
total 1111 msec for 0 tabs
0: Loaded
894: init start
217: browser.tabs.query, configs.$loaded
```

The output is the same for all seven of my opened window's sidebars.

Note that I cannot consistently reproduce the behaviour. This time, on startup with optimization enabled everything worked fine. I then disabled it and reenabled the option, toggling the extension on and off to ensure reloading) and the problem showed. Repeated toggling showed “infinite loading” one time after another, but after restarting Firefox I am not getting the problem to show up again.

**Comment by piroor** [comment]
@gonhidi Thanks a lot! I've realized that the initialization process is seems failed on very earlier step. It is completely unexpected result, so I deeply review initialization codes and found some dangerous cases. Could you collect debug log with the special build?:
https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we-debug.xpi

This build extremely report detailed logs around initialization. Here is instructions to collect debug logs, and please note that you need to activate "Debug mode":
https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-collect-debug-logs-of-tst

**Comment by alice0775** [comment]
Hi, I came from https://bugzilla.mozilla.org/show_bug.cgi?id=1460607#c20 ,

How can I get the debug log from startup of Browser?

**Comment by ksulli** [comment]
Today the problem is back for me too (TST 2.4.21, FF 60.0.1), i tried installing the xpi with debug, but I need a development / nighlty build of FF for that?

**Comment by SXZ1** [comment]
I've just come across this bug trying to restore my session with 10 000 tabs. Successfully fixed it by deleting **C:\Users\username\AppData\Local\Mozilla\Firefox\Profiles** folder.

Please note that this is not the folder where Firefox stores its profile data: all profile data is stored in ..\AppData\ **Roaming**

If you are afraid to delete this folder, just rename it.

**Comment by ksulli** [comment]
I installed FF Developer edition, installed the debug version of the extension, but I wasn't able to reproduce the problem. After going back to "normal" firefox, and reinstalling 2.4.21, I also stopped being able to reproduce the problem.

**Comment by RanHum** [comment]
On nightly 62.0a1 (2018-05-28) x64 i managed to reproduce the problem only on 10th time or something with [debug build](https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we-debug.xpi) with turned on debug in settings, but cannot catch logs from startup too, if that matters

**Comment by piroor** [comment]
@alice0775 Sorry that I forgot to take care of Browser's startup process. I've updated the debug build: https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we-debug.xpi and now you can see recent 1000 logs after startup process. On the remote debugger, please select the namespace `/sidebar/sidebar.html?...` and type `log.logs.join('\n')`, then stored logs will be printed.

**Comment by RanHum** [comment]
Got the same:
```
log.logs.join('\n')
"tst<?>:      Configs[storage] onMessage: Configs:request:locked ({type:\"Configs:request:locked\"}), ({id:\"treestyletab@piro.sakura.ne.jp\", url:\"moz-extension://82977df3-397b-46e9-b6cf-1b1e7653ac32/background/background.html\", envType:\"addon_child\", extensionId:\"treestyletab@piro.sakura.ne.jp\", contextId:412316860437})
tst<?>:         Configs[storage] load: successfully loaded local storage 
tst<?>:         Configs[storage] load: failed to load managed storage:  \"Error: Managed storage manifest not found\"
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:     initialize sidebar on load "
```

**Comment by piroor** [comment]
@alice0775 @RanHum Thanks a lot, now I've got what is the problem. TST waits forever on this line on your environment:
https://github.com/piroor/webextensions-lib-configs/blob/5e0ec520447f0403379c14686487655cac8b3b8a/Configs.js#L105

**Comment by piroor** [comment]
> ```javascript
>  try {
>    const lockedKeys = await browser.runtime.sendMessage({ type : 'Configs:request:locked' });
>    this.$log('load: successfully synchronized locked state');
>    return lockedKeys;
>  }
>  catch(e) {
>    this.$log('load: failed to synchronize locked state: ', String(e));
>  }
> ```

I expected that the promise returned by `browser.runtime.sendMessage()` is resolved or rejected immediately. However, actually the promise is not resolved and rejected, thus the `await` blocks all following operations.

**Comment by gonhidi** [comment]
@piroor I have not yet managed to reproduce the problem once more, but hopefully the debug output would be the same that has already been shared. If I were to stumble upon the problem and see a different output I will share it. Thank you and good job for having found the likely culprit!

**Comment by RanHum** [comment]
Can't reproduce after dozen attempts, here is [logs of successful load](https://pastebin.com/SrqnpEic).
I'll try to reproduce tomorrow with updated nightly, for me it happens nearly always after update, not so regularly within one build

**Comment by gonhidi** [comment]
Unfortunately I seem to have triggered the issue's symptoms with the current Tree Style Tab build, 2.4.23, both in the stable and the nightly Firefox, running on macOS. Going back to the latest debug build provided here (MD5: 62c38b3d63eb6dcbb0b18931e916113b) I got the following output when running `log.logs.join('\n')` from the remote extension debugger for any selected sidebar after disabling and reenabling the extension:

```
"tst<?>:         Configs[storage] load: successfully loaded local storage 
tst<?>:         Configs[storage] load: failed to load managed storage:  \"Error: Managed storage manifest not found\"
tst<?>:         Configs[storage] load: successfully synchronized locked state 
tst<?>:        Configs[storage] load: loaded for moz-extension://29fddb63-1fe7-e94f-bdd5-ef5b1c456226: ({localValues:{optionsExpandedSections:[\"section-appearance\", \"section-advanced\", \"section-debug\"], sidebarPosition:1, sidebarDirection:1, sidebarScrollbarPosition:0, style:\"mixed\", colorScheme:\"photon\", faviconizePinnedTabs:true, faviconizedTabScale:1.75, counterRole:2, baseIndent:12, minIndent:3, maxTreeLevel:-1, indentAutoShrink:true, indentAutoShrinkOnlyForVisible:true, scrollbarMode:3, narrowScrollbarSize:8, showContextualIdentitiesSelector:true, showNewTabActionSelector:true, longPressOnNewTabButton:\"contextual-identities-selector\", zoomable:false, showCollapsedDescendantsByTooltip:true, fakeContextMenu:true, context_reloadTree:true, context_reloadDescendants:true, context_closeTree:true, context_closeDescendants:true, context_closeOthers:true, context_collapseAll:true, context_expandAll:true, context_bookmarkTree:true, shouldDetectClickOnIndentSpaces:true, autoCollapseExpandSubtreeOnAttach:false, autoCollapseExpandSubtreeOnSelect:false, autoCollapseExpandSubtreeOnSelectExceptCurrentTabRemove:true, collapseExpandSubtreeByDblClick:false, autoExpandIntelligently:true, autoExpandOnCollapsedChildFocused:true, autoExpandOnTabSwitchingShortcuts:true, autoExpandOnTabSwitchingShortcutsDelay:800, autoExpandOnLongHover:true, autoExpandOnLongHoverDelay:500, autoExpandOnLongHoverRestoreIniitalState:true, skipCollapsedTabsForTabSwitchingShortcuts:false, parentTabBehaviorForChanges:0, syncParentTabAndOpenerTab:true, dropLinksOnTabBehavior:0, autoGroupNewTabs:false, autoGroupNewTabsTimeout:100, autoGroupNewTabsDelayOnNewWindow:500, autoGroupNewTabsFromPinned:true, insertNewChildAt:0, insertNewTabFromPinnedTabAt:-1, scrollToNewTabMode:1, scrollLines:3, autoAttach:true, autoAttachOnOpenedWithOwner:1, autoAttachOnNewTabCommand:3, autoAttachOnNewTabButtonMiddleClick:1, autoAttachOnDuplicated:3, autoAttachSameSiteOrphan:1, guessNewOrphanTabAsOpenedByNewTabCommand:true, guessNewOrphanTabAsOpenedByNewTabCommandUrl:\"about:newtab\", inheritContextualIdentityToNewChildTab:false, inheritContextualIdentityToSameSiteOrphan:true, closeParentBehavior:0, promoteFirstChildForClosedRoot:false, moveTabsToBottomWhenDetachedFromClosedParent:false, promoteAllChildrenWhenClosedParentIsLastChild:true, moveFocusInTreeForClosedCurrentTab:true, warnOnCloseTabs:false, lastConfirmedToCloseTabs:1518771684869, animation:true, smoothScrollEnabled:true, smoothScrollDuration:150, burstDuration:375, indentDuration:200, collapseDuration:150, outOfViewTabNotifyDuration:750, subMenuOpenDelay:300, subMenuCloseDelay:300, acccelaratedTabDuplication:false, enableWorkaroundForBug1409262:false, maximumAcceptableDelayForTabDuplication:10000, acceptableDelayForInternalFocusMoving:150, preventTearOffTabsTimeout:100, notificationTimeout:10000, startDragTimeout:400, minimumIntervalToProcessDragoverEvent:50, moveDroppedTabToNewWindowForUnhandledDragEvent:true, autoDiscardTabForUnexpectedFocus:false, knownExternalAddons:[\"multipletab@piro.sakura.ne.jp\"], cachedExternalAddons:[], notifiedFeaturesVersion:3, useCachedTree:true, simulateSVGContextFill:false, requestingPermissions:null, newTabAnimationDuration:100, userStyleRules:\"/* Show title of unread tabs with red and italic font */\\n/*\\n.tab.unread .label {\\n  color: red !important;\\n  font-style: italic !important;\\n}\\n*/\\n\\n/* Add private browsing indicator per tab */\\n/*\\n.tab.private-browsing .label:before {\\n  content: \\\"\\uD83D\\uDD76\\\";\\n}\\n*/\", debug:true, logOnUpdated:false, logOnMouseEvent:false, logOnScroll:false, logOnCollapseExpand:false, logOnCache:false, logOnFakeContextMenu:false, importedConfigsFromLegacy:null, legacyConfigsNextMigrationVersion:0, importedTreeStructureFromLegacy:null, migrateLegacyTreeStructure:true}, managedValues:null, lockedKeys:{}})
tst<?>:        Configs[storage] load: values are applied 
tst<?>:        Configs[storage] load: locked state is applied 
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:       l10s: apply ({})
tst<Sidebar-?>:     initialize sidebar on load 
tst<Sidebar-46>:         Configs[storage] load: successfully loaded sync storage "
```

For some reason, on subsequent disable-enable-log.logs.join('\n') tries (only a couple of them) I only seemed to get as output the last lines, from one of the `tst<Sidebar-?>:       l10s: apply ({})` onwards.

**Comment by piroor** [comment]
@gonhidi Could you add result of https://github.com/piroor/treestyletab/issues/1735#issuecomment-392656263 also?

**Comment by gonhidi** [comment]
@piroor 

The `log.logs.join('\n')` being the same as reported, the result of `gMetricsData.toString()` is the following:

```
"total 807 msec for 0 tabs
0: Loaded
766: init start
41: browser.tabs.query, configs.$loaded"
Webconsole context has changed
```

The reason that I have taken long to reply is because I cannot trigger the issue consistently: since my last report I have only had it happen this one time. Restarting Firefox with the cache option unticked and then marking it back again might be a temporary way to get things back on track, as opposed to unloading and then reloading the extension instead of quitting, but it lacks testing and I might be remembering wrong.

**Comment by GeryEmreis** [comment]
For me the tabs almost never load. Log from last debug is this:

````
tst<BG>: Configs[storage] load: failed to synchronize locked state: \"Error: Could not establish connection. Receiving end does not exist.\"
tst<BG>: Configs[storage] load: successfully loaded local storage
tst<BG>: Configs[storage] load: failed to load managed storage: \"Error: Managed storage manifest not found\" 
tst<BG>: Configs[storage] load: loaded for moz-extension://06952baf-a3f7-4347-a802-978995981f96: ({localValues:{optionsExpandedSections:[\"section-appearance\", \"section-newTab\", \"section-debug\", \"section-advanced\"], sidebarPosition:1, sidebarDirection:1, sidebarScrollbarPosition:0, style:\"plain\", colorScheme:\"system-color\", faviconizePinnedTabs:false, faviconizedTabScale:1.75, counterRole:2, baseIndent:12, minIndent:3, maxTreeLevel:-1, indentAutoShrink:true, indentAutoShrinkOnlyForVisible:true, scrollbarMode:1, narrowScrollbarSize:8, showContextualIdentitiesSelector:false, showNewTabActionSelector:true, longPressOnNewTabButton:\"contextual-identities-selector\", zoomable:false, showCollapsedDescendantsByTooltip:true, fakeContextMenu:true, context_reloadTree:true, context_reloadDescendants:false, context_closeTree:true, context_closeDescendants:false, context_closeOthers:false, context_collapseAll:true, context_expandAll:true, context_bookmarkTree:true, shouldDetectClickOnIndentSpaces:true, autoCollapseExpandSubtreeOnAttach:false, autoCollapseExpandSubtreeOnSelect:false, autoCollapseExpandSubtreeOnSelectExceptCurrentTabRemove:true, collapseExpandSubtreeByDblClick:false, autoExpandIntelligently:true, autoExpandOnCollapsedChildFocused:true, autoExpandOnTabSwitchingShortcuts:true, autoExpandOnTabSwitchingShortcutsDelay:800, autoExpandOnLongHover:true, autoExpandOnLongHoverDelay:500, autoExpandOnLongHoverRestoreIniitalState:true, skipCollapsedTabsForTabSwitchingShortcuts:true, parentTabBehaviorForChanges:0, syncParentTabAndOpenerTab:true, dropLinksOnTabBehavior:0, autoGroupNewTabs:false, autoGroupNewTabsTimeout:100, autoGroupNewTabsDelayOnNewWindow:500, autoGroupNewTabsFromPinned:true, insertNewChildAt:1, insertNewTabFromPinnedTabAt:-1, scrollToNewTabMode:1, scrollLines:3, autoAttach:true, autoAttachOnOpenedWithOwner:1, autoAttachOnNewTabCommand:0, autoAttachOnNewTabButtonMiddleClick:1, autoAttachOnDuplicated:3, autoAttachSameSiteOrphan:1, guessNewOrphanTabAsOpenedByNewTabCommand:true, guessNewOrphanTabAsOpenedByNewTabCommandUrl:\"about:newtab\", inheritContextualIdentityToNewChildTab:false, inheritContextualIdentityToSameSiteOrphan:true, closeParentBehavior:3, promoteFirstChildForClosedRoot:true, moveTabsToBottomWhenDetachedFromClosedParent:false, promoteAllChildrenWhenClosedParentIsLastChild:true, moveFocusInTreeForClosedCurrentTab:true, warnOnCloseTabs:false, lastConfirmedToCloseTabs:1523341513862, animation:true, smoothScrollEnabled:true, smoothScrollDuration:150, burstDuration:375, indentDuration:200, collapseDuration:150, outOfViewTabNotifyDuration:750, subMenuOpenDelay:300, subMenuCloseDelay:300, acccelaratedTabDuplication:false, enableWorkaroundForBug1409262:false, maximumAcceptableDelayForTabDuplication:10000, acceptableDelayForInternalFocusMoving:150, preventTearOffTabsTimeout:100, notificationTimeout:10000, startDragTimeout:400, minimumIntervalToProcessDragoverEvent:50, moveDroppedTabToNewWindowForUnhandledDragEvent:true, autoDiscardTabForUnexpectedFocus:false, knownExternalAddons:[\"multipletab@piro.sakura.ne.jp\"], cachedExternalAddons:[], notifiedFeaturesVersion:3, useCachedTree:true, simulateSVGContextFill:true, requestingPermissions:null, newTabAnimationDuration:100, userStyleRules:\"/* Show title of unread tabs with red and italic font */\\n/*\\n.tab.unread .label {\\n color: red !important;\\n font-style: italic !important;\\n}\\n*/\\n\\n/* Add private browsing indicator per tab */\\n/*\\n.tab.private-browsing .label:before {\\n content: \\\"\\uD83D\\uDD76\\\";\\n}\\n*/\", debug:false, logOnUpdated:false, logOnMouseEvent:false, logOnScroll:false, logOnCollapseExpand:false, logOnCache:false, logOnFakeContextMenu:false, importedConfigsFromLegacy:null, legacyConfigsNextMigrationVersion:0, importedTreeStructureFromLegacy:null, migrateLegacyTreeStructure:true}, managedValues:null, `lockedKeys:{}})
````
````
total 75 msec for 0 tabs
0: Loaded
52: init start
23: browser.tabs.query, configs.$loaded
````

**Comment by alice0775** [comment]
Regarding the issue in always private browsing mode, it will be fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1465537 .

**Comment by ksulli** [comment]
So today / yesterday i was able to reproduce the issue again - FF Developer Edition 62.0b6 (64-bit) + TreeStyleTab [debug] 2.4.21. Also - I tried to install the extension while I already was in a broken state, hopefully capturing the initialization logs.

```
gMetricsData.toString()
"total 2325 msec for 283 tabs
0: Loaded
36: init start
52: configs.$loaded
0: migrateLegacyConfigs
501: (async) parallel initialization tasks: waitUntilCompletelyRestored, retrieveAllContextualIdentities
811: restoreWindowFromEffectiveWindowCache start
26: restoreWindowFromEffectiveWindowCache start
58: restoreWindowFromEffectiveWindowCache start
80: restoreWindowFromEffectiveWindowCache start
0: restoreWindowFromEffectiveWindowCache start
3: restoreWindowFromEffectiveWindowCache start
1: restoreWindowFromEffectiveWindowCache start
277: restoreWindowFromEffectiveWindowCache fail
786: (async) rebuild 5
456: restoreWindowFromEffectiveWindowCache fail
1129: (async) rebuild 24
484: restoreWindowFromEffectiveWindowCache fail
1223: (async) rebuild 28
3: restoreWindowFromEffectiveWindowCache fail
1253: (async) rebuild 30
36: restoreWindowFromEffectiveWindowCache fail
1258: (async) rebuild 32
2: restoreWindowFromEffectiveWindowCache fail
1259: (async) rebuild 90"
```

Logs join:
```
log.logs.join('\n')
"tst<BG>:     Configs[storage] load: failed to load managed storage:  \"Error: Managed storage manifest not found\"
tst<BG>:     Configs[storage] load: successfully loaded local storage 
tst<BG>:     Configs[storage] load: failed to synchronize locked state:  \"Error: Could not establish connection. Receiving end does not exist.\"
tst<BG>:     Configs[storage] load: loaded for moz-extension://4e686934-3184-4b09-8871-327d831d45a2: ({localValues:{optionsExpandedSections:[\"section-appearance\", \"section-advanced\", \"section-debug\"], sidebarPosition:1, sidebarDirection:1, sidebarScrollbarPosition:0, style:\"flat\", colorScheme:\"photon\", faviconizePinnedTabs:true, faviconizedTabScale:1.75, counterRole:2, baseIndent:12, minIndent:3, maxTreeLevel:-1, indentAutoShrink:true, indentAutoShrinkOnlyForVisible:true, scrollbarMode:1, narrowScrollbarSize:8, showContextualIdentitiesSelector:false, showNewTabActionSelector:true, longPressOnNewTabButton:\"contextual-identities-selector\", zoomable:false, showCollapsedDescendantsByTooltip:true, fakeContextMenu:true, context_reloadTree:true, context_reloadDescendants:false, context_closeTree:true, context_closeDescendants:false, context_closeOthers:false, context_collapseAll:true, context_expandAll:true, context_bookmarkTree:true, shouldDetectClickOnIndentSpaces:true, autoCollapseExpandSubtreeOnAttach:false, autoCollapseExpandSubtreeOnSelect:false, autoCollapseExpandSubtreeOnSelectExceptCurrentTabRemove:false, collapseExpandSubtreeByDblClick:false, autoExpandIntelligently:true, autoExpandOnCollapsedChildFocused:true, autoExpandOnTabSwitchingShortcuts:true, autoExpandOnTabSwitchingShortcutsDelay:800, autoExpandOnLongHover:true, autoExpandOnLongHoverDelay:500, autoExpandOnLongHoverRestoreIniitalState:true, skipCollapsedTabsForTabSwitchingShortcuts:true, parentTabBehaviorForChanges:0, syncParentTabAndOpenerTab:true, dropLinksOnTabBehavior:0, autoGroupNewTabs:true, autoGroupNewTabsTimeout:100, autoGroupNewTabsDelayOnNewWindow:500, autoGroupNewTabsFromPinned:true, insertNewChildAt:1, insertNewTabFromPinnedTabAt:-1, scrollToNewTabMode:1, scrollLines:3, autoAttach:true, autoAttachOnOpenedWithOwner:1, autoAttachOnNewTabCommand:0, autoAttachOnNewTabButtonMiddleClick:1, autoAttachOnDuplicated:3, autoAttachSameSiteOrphan:1, guessNewOrphanTabAsOpenedByNewTabCommand:true, guessNewOrphanTabAsOpenedByNewTabCommandUrl:\"about:newtab\", inheritContextualIdentityToNewChildTab:false, inheritContextualIdentityToSameSiteOrphan:true, closeParentBehavior:0, promoteFirstChildForClosedRoot:false, moveTabsToBottomWhenDetachedFromClosedParent:false, promoteAllChildrenWhenClosedParentIsLastChild:true, moveFocusInTreeForClosedCurrentTab:true, warnOnCloseTabs:true, lastConfirmedToCloseTabs:1530278733628, animation:true, smoothScrollEnabled:true, smoothScrollDuration:150, burstDuration:375, indentDuration:200, collapseDuration:150, outOfViewTabNotifyDuration:750, subMenuOpenDelay:300, subMenuCloseDelay:300, acccelaratedTabDuplication:false, enableWorkaroundForBug1409262:false, maximumAcceptableDelayForTabDuplication:10000, acceptableDelayForInternalFocusMoving:150, preventTearOffTabsTimeout:100, notificationTimeout:10000, startDragTimeout:400, minimumIntervalToProcessDragoverEvent:50, moveDroppedTabToNewWindowForUnhandledDragEvent:true, autoDiscardTabForUnexpectedFocus:false, knownExternalAddons:[\"multipletab@piro.sakura.ne.jp\"], cachedExternalAddons:[], notifiedFeaturesVersion:3, useCachedTree:true, simulateSVGContextFill:true, requestingPermissions:null, newTabAnimationDuration:100, userStyleRules:\"/* Show title of unread tabs with red and italic font */\\n/*\\n.tab.unread .label {\\n  color: red !important;\\n  font-style: italic !important;\\n}\\n*/\\n\\n/* Add private browsing indicator per tab */\\n/*\\n.tab.private-browsing .label:before {\\n  content: \\\"\\uD83D\\uDD76\\\";\\n}\\n*/\\n\\n:root { --tab-height: 25px !important; }\\n.tab { height: 25px !important; }\\n\\n:root.left #tabbar.overflow,\\n#tabContextMenu,\\n#tabContextMenu ul {\\n  margin-left: -8px;\\n}\\n\\n:root.right #tabbar.overflow {\\n  margin-right: -8px;\\n}\", debug:false, logOnUpdated:true, logOnMouseEvent:true, logOnScroll:true, logOnCollapseExpand:true, logOnCache:true, logOnFakeContextMenu:true, importedConfigsFromLegacy:null, legacyConfigsNextMigrationVersion:0, importedTreeStructureFromLegacy:null, migrateLegacyTreeStructure:false}, managedValues:null, lockedKeys:{}})"
```

**Comment by ksulli** [comment]
I tried disabling and re-enabling the debug extension again (this time with debug mode enabled in the settings) and re-attaching the debugger. The actual log in the console is huge (hundreds of "build tab for" lines), but i tried filtering out some stuff that looks interesting to me - theres a single error message. Also, someone posted a very similar looking log to https://pastebin.com/80MbbQJC which i found by googling the error message.
```
tst<BG>:     Configs[storage] load: successfully loaded sync storage common.js:22:21
tst<Options>:     Configs[storage] load: successfully loaded sync storage common.js:22:21
tst<BG>:         restoreWindowFromEffectiveWindowCache start common.js:22:21
tst<BG>:         restoreWindowFromEffectiveWindowCache tabs:  
Array(283) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
...
tst<?>:     Configs[storage] load: failed to load managed storage:  Error: Managed storage manifest not found common.js:22:21
tst<BG>:      Configs[storage] onMessage: Configs:request:locked 
Object { type: "Configs:request:locked" }
 
Object { id: "treestyletab@piro.sakura.ne.jp", url: "moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/sidebar.html?style=flat", envType: "addon_child", extensionId: "treestyletab@piro.sakura.ne.jp", contextId: 274877929548 }
common.js:22:21 
...
tst<BG>:     restoreWindowFromEffectiveWindowCache: got from the owner [object Object] 
Object { cachedSignature: undefined, cache: undefined }
common.js:22:21
tst<BG>:     restoreWindowFromEffectiveWindowCache: verify cache for 5 
Object { cache: undefined, actualSignature: "tab-saucy-pangolin-1527156890434-64\ntab-oneiric-tahr-1527157057345-545\ntab-zesty-zapus-1527157847990-658\ntab-vivid-werwolf-1527158208090-193\ntab-breezy-meerkat-1527162031469-563\ntab-natty-lynx-1527162129968-966\ntab-precise-meerkat-1527162317784-52\ntab-agile-gibbon-1527162332439-455\ntab-dapper-ringtail-1527162344133-974\ntab-breezy-pangolin-1527162352485-794\ntab-edgy-koala-1527163583023-73\ntab-marveric-cat-1527164675186-974\ntab-utopic-pangolin-1527164687717-984\ntab-oneiric-alpaca-1527164784182-618\ntab-breezy-heron-1527165904335-181\ntab-intrepid-eft-1527164794614-657\ntab-breezy-narwhal-1527164924382-625\ntab-natty-yak-1527164986348-277\ntab-edgy-fawn-1529393042508-760\ntab-quantal-alpaca-1529060891093-636\ntab-cheerful-narwhal-1528468657740-307\ntab-gutsy-salamander-1527674860033-419\ntab-trusty-fawn-1527251127935-790\ntab-trusty-ringtail-1530618161114-762\ntab-yakkety-unicorn-1527281727066-172\ntab-oneiric-cat-1527165270934-82\ntab-jaunty-vervet-1527165379196-653\ntab-oneiric-werwolf-1527165382373-…", cachedSignature: undefined, signatureMatched: undefined }
common.js:22:21
tst<BG>:     restoreWindowFromEffectiveWindowCache: no effective cache for 5 common.js:22:21
tst<BG>:      clearWindowCache for owner  
Object { id: 1, index: 282, windowId: 5, highlighted: true, active: true, pinned: false, status: "complete", hidden: false, discarded: false, incognito: false, … }
 
Object { stack: "clearWindowCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/background/cache.js:121:63\nrestoreWindowFromEffectiveWindowCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/background/cache.js:56:5\n" }
common.js:22:21
tst<BG>:    build tabs for 5 from scratch
tst<BG>:     build tab for  
Object { id: 289, index: 0, windowId: 5, highlighted: false, active: false, pinned: false, status: "complete", hidden: false, discarded: true, incognito: false, … }
common.js:22:21 
...
tst<BG>:     build tab for  
Object { id: 1, index: 282, windowId: 5, highlighted: true, active: true, pinned: false, status: "complete", hidden: false, discarded: false, incognito: false, … }
common.js:22:21
tst<BG>:     restoreWindowFromEffectiveWindowCache: got from the owner [object Object] 
Object { cachedSignature: undefined, cache: undefined }
common.js:22:21
tst<BG>:     restoreWindowFromEffectiveWindowCache: verify cache for 24 
Object { cache: undefined, actualSignature: "tab-jaunty-alpaca-1523346837942-970\ntab-saucy-quetzal-1523346936264-212\ntab-yakkety-jackalope-1523346915888-568\ntab-warty-werwolf-1523347139432-450\ntab-breezy-vervet-1523347150314-899\ntab-vivid-ringtail-1523347165608-348\ntab-edgy-meerkat-1523347327136-305\ntab-xenial-ringtail-1523347737148-923\ntab-cheerful-yak-1523347169352-412\ntab-edgy-cat-1523347437662-858\ntab-lucid-alpaca-1523347549046-299\ntab-agile-alpaca-1523347558164-537\ntab-raring-gibbon-1523348319438-821\ntab-trusty-unicorn-1523348338874-95\ntab-xenial-tahr-1523348342244-609\ntab-oneiric-alpaca-1523348483290-145\ntab-marveric-quetzal-1523348489580-194\ntab-dapper-alpaca-1529568726905-616\ntab-marveric-drake-1528204451973-890\ntab-intrepid-salamander-1528189015259-261\ntab-marveric-vervet-1523348491970-444\ntab-oneiric-fawn-1523348567324-461\ntab-saucy-meerkat-1523428127940-625\ntab-oneiric-unicorn-1523428759686-146\ntab-marveric-unicorn-1523428885822-835\ntab-xenial-werwolf-1523429152328-583\ntab-lucid-pangolin-1523432250254-914\ntab-yakkety-g…", cachedSignature: undefined, signatureMatched: undefined }
common.js:22:21
tst<BG>:     restoreWindowFromEffectiveWindowCache: no effective cache for 24 common.js:22:21
tst<BG>:      clearWindowCache for owner  
Object { id: 1232, index: 288, windowId: 24, highlighted: false, active: false, pinned: false, status: "complete", hidden: false, discarded: false, incognito: false, … }
 
Object { stack: "clearWindowCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/background/cache.js:121:63\nrestoreWindowFromEffectiveWindowCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/background/cache.js:56:5\n" }
common.js:22:21
tst<BG>:    build tabs for 24 from scratch
...
tst<BG>:     build tab for  
Object { id: 1232, index: 288, windowId: 24, highlighted: false, active: false, pinned: false, status: "complete", hidden: false, discarded: false, incognito: false, … }
common.js:22:21
tst<BG>:     restoreWindowFromEffectiveWindowCache: got from the owner [object Object] 
Object { cachedSignature: "tab-breezy-zapus-1512027310963-720\ntab-yakkety-jackalope-1512027310956-105\ntab-agile-tahr-1512058664230-376\ntab-cheerful-heron-1526047290876-334\ntab-quantal-cat-1526047523382-171\ntab-raring-tahr-1526047556206-464\ntab-edgy-gibbon-1526047565428-663\ntab-breezy-tahr-1526049267606-341\ntab-breezy-fawn-1526047698670-387\ntab-karmic-gibbon-1526048537522-283\ntab-trusty-unicorn-1522217729346-830\ntab-vivid-zapus-1522757647348-918\ntab-zesty-xerus-1522761177026-122\ntab-vivid-unicorn-1522761139792-996\ntab-agile-cat-1522761630956-372\ntab-karmic-drake-1522762192468-148\ntab-zesty-fawn-1522762201308-29\ntab-natty-cat-1527257820362-297\ntab-feisty-cat-1523267943914-691\ntab-feisty-salamander-1524638011618-50\ntab-dapper-narwhal-1525270664388-322\ntab-precise-eft-1522939398268-499\ntab-oneiric-vervet-1525851395270-828\ntab-jaunty-drake-1525956584972-293\ntab-natty-koala-1526023787774-414\ntab-intrepid-zapus-1526659038266-549\ntab-raring-quetzal-1522765302466-715\ntab-saucy-heron-1522765353070-761\ntab-agile-salamander…", cache: {…} }
common.js:22:21
tst<BG>:     restoreWindowFromEffectiveWindowCache: cache for 26 is broken. 
Object { signature: "tab-breezy-zapus-1512027310963-720\ntab-yakkety-jackalope-1512027310956-105\ntab-agile-tahr-1512058664230-376\ntab-cheerful-heron-1526047290876-334\ntab-quantal-cat-1526047523382-171\ntab-raring-tahr-1526047556206-464\ntab-edgy-gibbon-1526047565428-663\ntab-breezy-tahr-1526049267606-341\ntab-breezy-fawn-1526047698670-387\ntab-karmic-gibbon-1526048537522-283\ntab-trusty-unicorn-1522217729346-830\ntab-vivid-zapus-1522757647348-918\ntab-zesty-xerus-1522761177026-122\ntab-vivid-unicorn-1522761139792-996\ntab-agile-cat-1522761630956-372\ntab-karmic-drake-1522762192468-148\ntab-zesty-fawn-1522762201308-29\ntab-natty-cat-1527257820362-297\ntab-feisty-cat-1523267943914-691\ntab-feisty-salamander-1524638011618-50\ntab-dapper-narwhal-1525270664388-322\ntab-precise-eft-1522939398268-499\ntab-oneiric-vervet-1525851395270-828\ntab-jaunty-drake-1525956584972-293\ntab-natty-koala-1526023787774-414\ntab-intrepid-zapus-1526659038266-549\ntab-raring-quetzal-1522765302466-715\ntab-saucy-heron-1522765353070-761\ntab-agile-salamander…", cache: "tab-breezy-zapus-1512027310963-720\ntab-yakkety-jackalope-1512027310956-105\ntab-agile-tahr-1512058664230-376\ntab-cheerful-heron-1526047290876-334\ntab-quantal-cat-1526047523382-171\ntab-raring-tahr-1526047556206-464\ntab-edgy-gibbon-1526047565428-663\ntab-breezy-tahr-1526049267606-341\ntab-breezy-fawn-1526047698670-387\ntab-karmic-gibbon-1526048537522-283\ntab-trusty-unicorn-1522217729346-830\ntab-vivid-zapus-1522757647348-918\ntab-zesty-xerus-1522761177026-122\ntab-vivid-unicorn-1522761139792-996\ntab-agile-cat-1522761630956-372\ntab-karmic-drake-1522762192468-148\ntab-zesty-fawn-1522762201308-29\ntab-natty-cat-1527257820362-297\ntab-feisty-cat-1523267943914-691\ntab-feisty-salamander-1524638011618-50\ntab-dapper-narwhal-1525270664388-322\ntab-precise-eft-1522939398268-499\ntab-oneiric-vervet-1525851395270-828\ntab-jaunty-drake-1525956584972-293\ntab-natty-koala-1526023787774-414\ntab-intrepid-zapus-1526659038266-549\ntab-raring-quetzal-1522765302466-715\ntab-saucy-heron-1522765353070-761\ntab-agile-salamander…" }
common.js:22:21
tst<BG>:      clearWindowCache for owner  26 
Object { stack: "clearWindowCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/background/cache.js:121:63\nrestoreWindowFromEffectiveWindowCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/background/cache.js:36:5\n" }
common.js:22:21
tst<BG>:     restoreWindowFromEffectiveWindowCache: got from the owner [object Object] 
Object { cachedSignature: "tab-trusty-eft-1531119220375-778", cache: {…} }
common.js:22:21 
```
and this continues for my other windows.

At the end, there are multiple logs about configs storage *and then there is a single error message*
```
tst<?>:     Configs[storage] load: loaded for moz-extension://4e686934-3184-4b09-8871-327d831d45a2: 
Object { localValues: {…}, managedValues: null, lockedKeys: {} }
common.js:22:21
tst<?>:     Configs[storage] load: values are applied common.js:22:21
tst<?>:     Configs[storage] load: locked state is applied common.js:22:21
tst<?>:     Configs[storage] load: successfully synchronized locked state common.js:22:21
tst<?>:     Configs[storage] load: loaded for moz-extension://4e686934-3184-4b09-8871-327d831d45a2: 
Object { localValues: {…}, managedValues: null, lockedKeys: {} }
common.js:22:21
tst<?>:     Configs[storage] load: values are applied common.js:22:21
tst<?>:     Configs[storage] load: locked state is applied common.js:22:21
```
```
Error: Incorrect argument types for sessions.removeTabValue. cache.js:112:12
```
```
tst<?>:     Configs[storage] load: successfully loaded sync storage
common.js:22:21
tst<Sidebar-?>:     Configs[storage] load: successfully loaded sync storage
common.js:22:21
tst<Sidebar-?>:      l10s: apply 
title="Open a new tab as…"
common.js:22:21 
...

tst<Sidebar-?>:      l10s: apply 
title="&Close Tab"
common.js:22:21
tst<Sidebar-?>:    initialize sidebar on load
common.js:22:21
Navigated to moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/sidebar.html?style=flat
gMetricsData.toString()
"total 420 msec for 0 tabs
0: Loaded
362: init start
58: browser.tabs.query, configs.$loaded"
Webconsole context has changed
```

So, i tried adding debugging information to the suspect method:
```javascript
function updateWindowCache(aOwner, aKey, aValue) {
  if (!aOwner ||
      !getTabById(aOwner))
    return;
  if (aValue === undefined) {
    //return browser.sessions.removeWindowValue(aOwner, aKey);
	logForCache(`updateWindowCache: `, {
      aOwner: aOwner,
	  aOwnerId: aOwner.id,	
      aKey:     aKey,
	  aValue:   aValue
    })
    return browser.sessions.removeTabValue(aOwner.id, aKey);
  }
  else {
    //return browser.sessions.setWindowValue(aOwner, aKey, aValue);
    return browser.sessions.setTabValue(aOwner.id, aKey, aValue);
  }
}
```
Unfortunately, this required several restarts before I got it right, and the extension seems to have sorted itself out... and the log now looks completely different, instead of many hundreds of :build tab from scratch" messages, I'm now seeing instead messages like
```
tst<Sidebar-36>:     applyTreeStructureToTabs:  
Array [ "#tab-36-4" ]
 
Array [ {…} ]
 
Object {  }
common.js:22:21
tst<Sidebar-36>:      detachTab:  #tab-36-4 
Object { justNow: true }
 
Object { stack: "detachTab@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/common/tree/tree-operations.js:256:19\napplyTreeStructureToTabs@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/common/tree/tree-operations.js:1661:5\ninheritTreeStructure@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/sidebar.js:496:11\n\n" }
common.js:22:21
tst<Sidebar-36>:      parent is already removed, or orphan tab common.js:22:21
tst<Sidebar-36>:     expandStates:  
Array [ true ]
common.js:22:21
tst<Sidebar-36>:      reserveToUpdateCachedTabbar  
Object { stack: "reserveToUpdateCachedTabbar@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:207:56\ninit@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/sidebar.js:203:5\n" }
common.js:22:21
tst<Sidebar-36>:       clearWindowCache  
Object { stack: "clearWindowCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:164:45\nreserveToUpdateCachedTabbar@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:209:3\ninit@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/sidebar.js:203:5\n" }
common.js:22:21
tst<Sidebar-36>:    Startup metrics:  total 63516 msec for 1 tabs
0: Loaded
43489: init start
1724: browser.tabs.query, configs.$loaded
1611: applyStyle, waitUntilBackgroundIsReady and retrieveAllContextualIdentities
1: getEffectiveWindowCache start
21: (async) calculateDefaultSizes
8: (async) initializing contextual identities
3: (async) tabContextMenu.init
360: (async) getting kWINDOW_STATE_SCROLL_POSITION
970: getEffectiveWindowCache get {"cache":false}
3: getEffectiveWindowCache fail
973: (async) read cached sidebar contents
955: (async) getting registered addons and scroll lock state
2299: rebuildAll (from scratch)
13391: inheritTreeStructure: kCOMMAND_PULL_TREE_STRUCTURE
0: applyTreeStructureToTabs: start
1: applyTreeStructureToTabs: preparation
1: applyTreeStructureToTabs: attach/detach
1: applyTreeStructureToTabs: collapse/expand
0: inheritTreeStructure: applyTreeStructureToTabs
13392: (async) inheritTreeStructure
1: start to listen events
11: apply configs
16680: (async) main
16658: (async) parallel initialization tasks
13: init end
tst<Sidebar-30>:     applyTreeStructureToTabs:  
Array(32) [ "#tab-30-1190", "#tab-30-1191", "#tab-30-1192", "#tab-30-1193", "#tab-30-1194", "#tab-30-1195", "#tab-30-1196", "#tab-30-1197", "#tab-30-1198", "#tab-30-1199", … ]
 
Array(32) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
 
Object {  }
common.js:22:21
tst<Sidebar-30>:      detachTab:  #tab-30-1190 
Object { justNow: true }
 
Object { stack: "detachTab@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/common/tree/tree-operations.js:256:19\napplyTreeStructureToTabs@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/common/tree/tree-operations.js:1661:5\ninheritTreeStructure@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/sidebar.js:496:11\n\n" }
common.js:22:21
tst<Sidebar-30>:      parent is already removed, or orphan tab common.js:22:21
tst<Sidebar-30>:      detachTab:  #tab-30-1191 
Object { justNow: true }
 
Object { stack: "detachTab@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/common/tree/tree-operations.js:256:19\napplyTreeStructureToTabs@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/common/tree/tree-operations.js:1661:5\ninheritTreeStructure@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/sidebar.js:496:11\n\n" }
common.js:22:21
tst<Sidebar-30>:      parent is already removed, or orphan tab common.js:22:21
tst<Sidebar-30>:      attachTabTo:  
Object { child: "#tab-30-1191", parent: "#tab-30-1190", children: null, insertAt: undefined, insertBefore: "<NULL>", insertAfter: "<NULL>", dontMove: true, dontUpdateIndent: undefined, forceExpand: undefined, dontExpand: true, … }
common.js:22:21
tst<Sidebar-30>:      reference tabs:  
Object { next: "#tab-30-1192", prev: "#tab-30-1190" }
```
and this
```
tst<Sidebar-30>:    Startup metrics:  total 63683 msec for 32 tabs
0: Loaded
43381: init start
2292: browser.tabs.query, configs.$loaded
1074: applyStyle, waitUntilBackgroundIsReady and retrieveAllContextualIdentities
0: getEffectiveWindowCache start
14: (async) calculateDefaultSizes
6: (async) initializing contextual identities
2: (async) tabContextMenu.init
382: (async) getting kWINDOW_STATE_SCROLL_POSITION
947: getEffectiveWindowCache get {"cache":false}
7: getEffectiveWindowCache fail
955: (async) read cached sidebar contents
942: (async) getting registered addons and scroll lock state
2340: rebuildAll (from scratch)
13449: inheritTreeStructure: kCOMMAND_PULL_TREE_STRUCTURE
1: applyTreeStructureToTabs: start
1: applyTreeStructureToTabs: preparation
96: applyTreeStructureToTabs: attach/detach
16: applyTreeStructureToTabs: collapse/expand
0: inheritTreeStructure: applyTreeStructureToTabs
13562: (async) inheritTreeStructure
2: start to listen events
45: apply configs
16906: (async) main
16890: (async) parallel initialization tasks
6: applying scroll position
26: init end common.js:22:21
tst<Sidebar-30>:    scroll to current tab on updateTabbarLayout common.js:22:21
tst<Sidebar-36>:      reserveToUpdateCachedTabbar  
Object { stack: "reserveToUpdateCachedTabbar@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:207:56\nonTabLevelChanged@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/handlers.js:989:3\n" }
common.js:22:21
tst<Sidebar-36>:       clearWindowCache  
Object { stack: "clearWindowCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:164:45\nreserveToUpdateCachedTabbar@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:209:3\nonTabLevelChanged@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/handlers.js:989:3\n" }
common.js:22:21
tst<Sidebar-30>:      reserveToUpdateCachedTabbar  
Object { stack: "reserveToUpdateCachedTabbar@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:207:56\nonTabLevelChanged@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/handlers.js:989:3\n" }
common.js:22:21
tst<Sidebar-30>:       clearWindowCache  
Object { stack: "clearWindowCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:164:45\nreserveToUpdateCachedTabbar@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:209:3\nonTabLevelChanged@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/handlers.js:989:3\n" }
common.js:22:21
tst<Sidebar-30>:      reserveToUpdateCachedTabbar  
Object { stack: "reserveToUpdateCachedTabbar@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:207:56\nonTabLevelChanged@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/handlers.js:989:3\n" }
common.js:22:21
tst<Sidebar-30>:       clearWindowCache  
Object { stack: "clearWindowCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:164:45\nreserveToUpdateCachedTabbar@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:209:3\nonTabLevelChanged@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/handlers.js:989:3\n" }
common.js:22:21
tst<Sidebar-30>:      reserveToUpdateCachedTabbar  
Object { stack: "reserveToUpdateCachedTabbar@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:207:56\nonTabLevelChanged@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/handlers.js:989:3\n" }
common.js:22:21
tst<Sidebar-30>:       clearWindowCache  
Object { stack: "clearWindowCache@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:164:45\nreserveToUpdateCachedTabbar@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:209:3\nonTabLevelChanged@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/handlers.js:989:3\n" }
common.js:22:21
tst<Sidebar-30>:      reserveToUpdateCachedTabbar  
Object { stack: "reserveToUpdateCachedTabbar@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/cache.js:207:56\nonTabLevelChanged@moz-extension://4e686934-3184-4b09-8871-327d831d45a2/sidebar/handlers.js:989:3\n" }
common.js:22:21
... repeated many times...
```

**Comment by piroor** [comment]
@ksulli Thanks, but 2.4.21 is outdated so the problem can be solved in recent versions. Could you try with the latest development build?

**Comment by ksulli** [comment]
@piroor the problem started in 2.4.23 (production version), so i switched over to the FF debug edition and got the debug version freshly from https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we-debug.xpi (which is now returning a 404) and 2.4.21 was the version reported by the debug XPI.

I see that 2.4.24 of the production build was updated yesterday.... so i'll wait if the problem appears again.

**Comment by torevor** [comment]
I am on 2.4.24 and still encountering this problem.

**Comment by Blackkatt** [comment]
Running 62.0 (64-bit) in Windows 10 and its still a problem =(

**Comment by ksulli** [comment]
I have a feeling that this problem appears basically after every FF update - yesterday I restarted the browser, noticed it got updated  and the problem reappeared (basically the whole browser is frozen). After a few restarts it somehow sorts itself out, rebuilds the tree cache and then its hard to reproduce until the next FF update.

**Comment by piroor** [comment]
I've tried updating of Firefox itself with following steps, but I couldn't reproduce this problem:

 1. Install Firefox 63.0.3.
 2. Start Firefox with clean profile.
 3. Install TST 2.6.8.
 4. Open "About" dialog and update Firefox to 64.0.
 5. Restart Firefox.

I tried with just few tabs, so I think that some opened (long-live) tabs or the total number of tabs on your environment may be a part of the conditions to reproduce the probelm.

**Comment by khushman1** [comment]
I am facing this issue intermittently on 
TST 3.0.5
FF 66.0.1
Arch x86_64

Disabling and reenabling fixes the issue for some time.

I will try to catch debug logs if it happens again and post.

P.S. Thanks for the awesome addon! :)

**Comment by piroor** [comment]
@khushman1 This thread is old, and there is another active one #2200. Could you join to there? Steps to collect debug information is: https://github.com/piroor/treestyletab/issues/2200#issuecomment-476960598

**Comment by piroor** [comment]
I close this because outdated.
