### ISSUE TITLE
[Bug] Dragging collapsed folders sometimes results in tabs leaving tab folder/group hierachy

### ISSUE THREAD

**Issue by NefariousFerris** [piroor/treestyletab#3567]
Attached is an example of a group hierachy that I dragged, while the parent group was collapsed. And another example of what ends up happening when moved to a different window

![Screenshot 2024-06-03 114234](https://github.com/piroor/treestyletab/assets/73053278/376ced84-1eb4-4d70-ad1b-d3233d918cf4)

![Screenshot 2024-06-03 114339](https://github.com/piroor/treestyletab/assets/73053278/682548ff-2957-4bd0-bc77-3c004fd4d2b8)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
I missed this case if those group tabs have any checked "Close this tab when...". TST cleans them up automatically while tabs are moved across windows because those tabs lose their children while moving tabs. I've implemented a mechanism to block unexpected cleaning of group tabs with no children with the commit df3a27b.

**Comment by NefariousFerris** [comment]
thank you @piroor , any way to disable that button being checked? I actually hate always try to uncheck that option, but it's the default with the "Operate Tabs" context menu function when creating a new group from tabs. Looked through the TST and TST more command settings but can't figure out a way to disable it

**Comment by piroor** [comment]
TST options => checking "Unlock Expert Options" => "New Tabs not from Existing Tabs" => "Default state of group tabs for each context" section has options for that.

**Comment by NefariousFerris** [comment]
@piroor  thank you so much! I did change all 3 options to "check to nothing" but it still happening

**Comment by piroor** [comment]
How did you open group tabs? Those options affects only to group tabs newly opened by TST itself. For example, group tabs will have checked state even you change those options, if you open a group tab from a bookmark and its URL contains query options for checkboxes. (And of course, changing those options won't affect to existing group tabs.)

**Comment by NefariousFerris** [comment]
I am right clicking and doing it through the menu provided by the TST more command extension
![image](https://github.com/piroor/treestyletab/assets/73053278/edfa1028-68de-44ea-bffa-dc3361cb8826)

**Comment by piroor** [comment]
Ah, I didn't provide similar options to the addon...

**Comment by NefariousFerris** [comment]
Is there an easier way you would recommend?

**Comment by piroor** [comment]
It is not controllable from TST More Tree Commands for now, so I've introduced some changes ba82187 and added a new option to TST side: "Opened to group tabs from other addons via API". It will be available at the next release.

**Comment by NefariousFerris** [comment]
Thank you so much!! Can't wait!

**Comment by NefariousFerris** [comment]
Thank you for pushing this so quick. I am now have a new issue where if I drag tabs to a folder that is collapsed, sometimes the tabs that were already in that folder end up in the folder below that folder.
